version: '3'
services:
  ollama:
    image: ollama/ollama
    ports:
      -  11434:11434
    volumes:
      - ./data:/root/.ollama
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      -  8080:8080
    volumes:
      - ./open-webui:/app/backend/data
    environment:
      -  OLLAMA_BASE_URL=http://ollama:11434
    tty: true

